<script src="<?php echo e(asset('dist/js/jquery-3.6.0.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/popper.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/tooltip.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/bootstrap.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/jquery.nicescroll.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/moment.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/stisla.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/jscolor.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/bootstrap-datepicker.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/bootstrap-timepicker.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/bootstrap-tagsinput.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/select2.full.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/summernote-bs4.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/jquery.dataTables.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/dataTables.bootstrap4.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/iziToast.min.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/fontawesome-iconpicker.js')); ?>"></script>
<script src="<?php echo e(asset('dist/js/bootstrap4-toggle.min.js')); ?>"></script><?php /**PATH C:\xampp\htdocs\project\online_room_booking\resources\views/admin/layout/scripts.blade.php ENDPATH**/ ?>